# Generated by Django 5.1.7 on 2025-03-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0002_labour_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='labour_image/'),
        ),
    ]
