# Generated by Django 5.1.7 on 2025-03-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrial',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='matrial_image'),
        ),
    ]
